// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID                 int            `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name               string         `gorm:"column:name;primaryKey" json:"name"`
	Email              string         `gorm:"column:email;primaryKey" json:"email"`
	Password           string         `gorm:"column:password" json:"password"`
	ConfirmSelector    string         `gorm:"column:confirm_selector" json:"confirm_selector"`
	ConfirmVerifier    string         `gorm:"column:confirm_verifier" json:"confirm_verifier"`
	Confirmed          bool           `gorm:"column:confirmed" json:"confirmed"`
	AttemptCount       int            `gorm:"column:attempt_count" json:"attempt_count"`
	LastAttempt        *time.Time     `gorm:"column:last_attempt" json:"last_attempt"`
	Locked             *time.Time     `gorm:"column:locked" json:"locked"`
	RecoverSelector    string         `gorm:"column:recover_selector" json:"recover_selector"`
	RecoverVerifier    string         `gorm:"column:recover_verifier" json:"recover_verifier"`
	RecoverTokenExpiry *time.Time     `gorm:"column:recover_token_expiry" json:"recover_token_expiry"`
	OAuth2UID          string         `gorm:"column:OAuth_2_uid" json:"OAuth_2_uid"`
	OAuth2Provider     string         `gorm:"column:OAuth_2_provider" json:"OAuth_2_provider"`
	OAuth2AccessToken  string         `gorm:"column:OAuth_2_access_token" json:"OAuth_2_access_token"`
	OAuth2RefreshToken string         `gorm:"column:OAuth_2_refresh_token" json:"OAuth_2_refresh_token"`
	OAuth2Expiry       *time.Time     `gorm:"column:OAuth_2_expiry" json:"OAuth_2_expiry"`
	TOTPSecretKey      string         `gorm:"column:TOTP_Secret_key" json:"TOTP_Secret_key"`
	SMSPhoneNumber     string         `gorm:"column:SMS_phone_number" json:"SMS_phone_number"`
	SMSSeedPhoneNumber string         `gorm:"column:SMS_seed_phone_number" json:"SMS_seed_phone_number"`
	RecoveryCodes      string         `gorm:"column:recovery_codes" json:"recovery_codes"`
	UserID             int            `gorm:"column:user_id;primaryKey" json:"user_id"`
	BardID             int            `gorm:"column:bard_id;primaryKey" json:"bard_id"`
	CreatedTime        int64          `gorm:"column:created_time;not null" json:"created_time"`
	DeletedTime        gorm.DeletedAt `gorm:"column:deleted_time" json:"deleted_time"`
	ModifiedTime       int64          `gorm:"column:modified_time;not null" json:"modified_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
